name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 19.x, 20.x, 21.x]
        mongodb-version: ['5.0', '6.0', '7.0']

    steps:
    - name: Git checkout
      uses: actions/checkout@v4

    - name: Use Node.js '20.x'
      uses: actions/setup-node@v4
      with:
        node-version: 16.x
        cache: 'npm'

    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.10.0
      with:
        mongodb-version: 16.x

    - name: Install dependencies 
      run: npm ci
    
    - name: Running tests
      run: npm test